### ISSUE TITLE
Asking for feedback

### ISSUE THREAD

**Issue by acstll** [acstll/chopped-middleware#1]
@gaearon

I came up with this a few days ago and wanted to share it with you. I ping you here to not troll Redux’s Github issues and to keep it quiet. I won’t advertise it either, just link it on the Chopped Redux page when the README is complete.

The **whole point** of this is to make Middleware easier to grasp and understand (whether you’re a newcomer or have some FP experience).

So, instead of this:

``` js
// ES2015
const foo = store => next => action => {
  next(action);
};

// ES5
var foo = function (store) {
  return function (next) {
    return function (action) {
      next(action);
    }
  }
};
```

You have this:

``` js
// ES2015 and ES5
function foo (action, next) {
  next();
}
```

If you need store methods you get them from context:

``` js
function foo (action, next) {
  const { getState, dispatch } = this;
  next();
}
```

Hope you find this useful.

**Comment by gaearon** [comment]
Feel free to propose in the main repo. :-)

**Comment by acstll** [comment]
I will :+1:
